<?php

namespace AppBundle\Repository;

/**
 * LivreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreRepository extends \Doctrine\ORM\EntityRepository
{
    public function countCategoryQuery(){
        return $query = $this->createQueryBuilder('formationAlias')
            ->select(COUNT('formationAlias.*'))
            ->groupBy('formationAlias.categories.name')
            ->getQuery()
            ->getResult();
    }

}
