<?php

namespace AppBundle\Repository;

/**
 * modulesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class modulesRepository extends \Doctrine\ORM\EntityRepository
{
}
